### PR TITLE
handled no router provided

### PR DESCRIPTION
**Pull request by doeixd**

### CODE REVIEW

**Comment by nksaraf** [comment]
Instead of throwing an error maybe its a better idea to add a default router with some instructions for what to do add a router. Just so that we don't blow up the server at the beginning and allows the user to gracefully experience the tool. 

This will go well along with getting proper file watching for the app.config.js itself. So show the user a missing routers page and give instructions for what code to put in the app.config.js file. Then when they do that, we should be able to reload the client to see the router added by the user.

**Comment by doeixd** [comment]
How should that page be served/what should the default router look like?

Would this work? A simple `index.html` file located somewhere like `node_modules/vinxi/lib/default/index.html` paired with the following as the default router: 
```js
const fallbackRouter = {
    name: "fallback-router",
    base: "/",
    mode: "static",
    dir: "node_modules/vinxi/lib/default/"
}
```

**Comment by nksaraf** [comment]
Yeah that's probably a cool idea. We can have cool looking default index.html!

**Comment by nksaraf** [comment]
Closing now until we have some more concrete ideas for what to do for empty router. Right now we setup a vite app and still depend on the user creating the files. What we probably need is a proper designed home screen for all the examples

**Pull request closed without merging**
