### PR TITLE
Bump to Vite 6

### PR DESCRIPTION
**Pull request by birkskyum**
Finally, the vite 6 is out

https://github.com/vitejs/vite/blob/v6.0.0/packages/vite/CHANGELOG.md

I know it'll probably trigger a larger refactor of Vinxi to use the Env API, but in the meantime it would be nice to land these improvements in solid start etc.

### CODE REVIEW

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by birkskyum** [comment]
I added as a major, just to avoid breaking anything that updates automatically.

**Comment by nksaraf** [comment]
Do we know why the builds might be failing? if we can debug that, we are good to go, I don't think there are any big breaking changes in vite 6 as far as I know.

**Comment by nksaraf** [comment]
We don't want to go 1.0, yet, this will have be a minor (also there aren't really any big changes), until we actually integrate the environments API, then we can go to 1.0, I feel like there could be some API changes on our side when we do that.

**Comment by birkskyum** [comment]
I don't think there are big breaking changes in vite 6 either - the adaption needed happened in vite-plugin-solid, which can be readily updated for the examples.

**Pull request merged**
