### PR TITLE
fix: set WebEventContext on calls to `toWebRequest` to prevent h3 body utils calls from blocking

### PR DESCRIPTION
**Pull request by edivados**
I assume this is related to the problem faced in Solid-Start where one would encounter errors with toWebRequest or H3 utility functions blocking forever.

Reasons this should be restored.

1. Request object initialization accesses the body prop and triggers the getter.
2. Changes behavior of `toWebRequest` not returning `event.web.request` anymore if present.

https://github.com/unjs/h3/blob/ae91fc8658315dca75da22b665eda4175eef7ea8/src/utils/request.ts#L181

#### Ways to solve the multiple call to `toWebRequest`

1. Call once, cache and don't call again (What Solid-Start is doing now)
2. Call and set WebRequestContext on the H3Event (Solid-Start does this on top of 1)

Setting the WebRequestContext has the following effects:

1. toWebRequest will return the value on event.web if present instead of creating a new Request object
2. Most body related utlity functions will use event.web instead of event.node.req

The lack of documentation is unfortunate. For example `readBody` caches and parses the body. So it is safe to be called multiple times.

References:

 - https://github.com/solidjs/solid-start/issues/1165

### CODE REVIEW

**Comment by nksaraf** [comment]
But this did fix things in solid start. Are they fixed independent of this ? If it's a good idea to set WebRewhestContext on h3event then we should do that internally. This has caused a lot of issues.

**Comment by edivados** [comment]
Ryan did what I described in 1 and 2 a while ago. You just recently published this change no? I would have to look for the exact commits.

https://github.com/solidjs/solid-start/blob/a670ffa3c498af6d16f44a4156edaca9d1fbc155/packages/start/server/middleware.ts#L43

https://github.com/solidjs/solid-start/blob/a670ffa3c498af6d16f44a4156edaca9d1fbc155/packages/start/server/middleware.ts#L21

>If it's a good idea to set WebRewhestContext on h3event then we should do that internally

Yes, vinxi could provide a `toWebRequest` that sets the web context and that would make it safe to call multiple times. In my opinion vinxi shouldn't touch any h3 utilities unless absolutely necessary. In this case the issue is simply solved downstream by not calling `toWebRequest` more than once per request.

**Comment by edivados** [comment]
Also solution 1 doesn't fully solve the blocking problem I belive. If someone decides to call i.e. `readBody` after a call to `toWebRequest` without setting the web context the h3 utilities would try to read `event.node.req` and block. It would only works for Solid-Start if no one ever calls readBody(apiEvent) and only does `apiEvent.request`.

**Comment by nksaraf** [comment]
> Ryan did what I described in 1 and 2 a while ago. You just recently published this change no? I would have to look for the exact commits.
> 
> [solidjs/solid-start@`a670ffa`/packages/start/server/middleware.ts#L43](https://github.com/solidjs/solid-start/blob/a670ffa3c498af6d16f44a4156edaca9d1fbc155/packages/start/server/middleware.ts#L43)
> 
> [solidjs/solid-start@`a670ffa`/packages/start/server/middleware.ts#L21](https://github.com/solidjs/solid-start/blob/a670ffa3c498af6d16f44a4156edaca9d1fbc155/packages/start/server/middleware.ts#L21)
> 
> > If it's a good idea to set WebRewhestContext on h3event then we should do that internally
> 
> Yes, vinxi could provide a `toWebRequest` that sets the web context and that would make it safe to call multiple times. In my opinion vinxi shouldn't touch any h3 utilities unless absolutely necessary. In this case the issue is simply solved downstream.

how I think about it is that vinxi shouldn't hav any server runtim issues. Don't want it solvd downstream in solid-start, if it's going to be a problem all vinxi users face. 

I am also okay wrapping h3 utils where it makes sens and actually try to push the fixes upstream.

**Comment by edivados** [comment]
In this case my suggestion would be to provide your own `toWebRequest` and set `event.web`. Unfortunately this stuff is not documented so I am basing verything on what I saw in H3's implementation.

Adding a test around this should be possible. A middleware and server function should show the problem and if it is fixed or not.

**Comment by edivados** [comment]
@nksaraf I can still reproduce the blocking. I will add a test here and we can go from there.

**Comment by nksaraf** [comment]
Were we able to fix the last bugs related to the blocking? is there a test for that?

**Comment by edivados** [comment]
It addresses the blocking that was caused for the same reason it was in start. Adding the fix to `toWebRequest` internally. At least a single call to `toWebRequest` shouldn't make body utils like `readBody` instantly unusable.

I added a test here.

The order of things to cause the block is this.

1. Call toWebRequest (without asigning event.web) - Start did this in middleware wrapper
2. Call  h3`s `readBody` - Happens in server fn handler

The result is the block.

**Comment by nksaraf** [comment]
Okay so then its ready to merge if that test passed I'm assuming?? Just confirm this

> The h3 body ultils not throwing is a bit strange.

You're suggesting `h3` should have popped an error for this, and it just blocks and stays stuck. Maybe this will need to upstreamed at some point. Ill look into that.

**Pull request merged**
