### PR TITLE
Fix style order in dev mode

### PR DESCRIPTION
**Pull request by elite174**
This fixes the following bug: https://github.com/solidjs/solid-start/issues/1478

I understand that it was an attempt to avoid FOUC, but it should be done better, because resulting style order is wrong. Also it eliminates duplication of styles in dev mode.

### CODE REVIEW

**Comment by elite174** [comment]
@nksaraf please, have a look at this. For now it's really a problem to develop with incorrect style ordering.

**Comment by nksaraf** [comment]
Yup just looking at this with the other css fixes together, there's more fixes to do with reference counting and preloading. Will be released in a day or two

**Comment by elite174** [comment]
Still waiting... 👀

**Comment by elite174** [comment]
Any updates on this?

@nksaraf

**Pull request merged**
