### PR TITLE
feat: make https configurable for dev

### LINKED ISSUE #81: dev-server on https
I'm porting solid-start application from 0.3 to 0.4. Previously, I could specify this in vite.config and dev-server started to work over https, which is really useful for my scenarios.

```js
{
  server: {
    https: {
      cert: 'file.pem',
      key: 'file-key.pem'
    }
  }
}
```

I don't need this for production, which uses reverse-proxies in my case. But for dev-server this is very important.

### PR DESCRIPTION
**Pull request by edivados**
This allows to set SSL cert and key for https. closes #81

```js
{
  server: {
    https: {
      cert: "cert or path", 
      key: "key or path"
    }
  }
}
```

Please review.
- Should serveConfig be based to router-modes instead of only https options?
- Types

It would be cool to also support generating a cert by just setting https to true at some point. listhen has a this function `resolveCertificate` that does all the nice things and returns `{ cert, key }` but is unfortunately internal.

### CODE REVIEW

**Comment by nksaraf** [comment]
Yeah I would want just https to work. Lets work with listhen to expose that, and in the meanwhile copy over that code and do it ourselves here?

Does listehn support https: true ?

**Comment by nksaraf** [comment]
since https is a server concern it should be handled centrally. Why cant we just set the https field in the `createViteHandler` in the `dev-server.js`. We don't need to inform each build handler and dev handler. We can centralize this.

**Comment by indeyets** [comment]
@edivados will it still be possible to specify cert/key manually? :)

**Comment by edygar** [comment]
@nksaraf should it supported `http: true`? I'm asking because of [it got removed from vite 5](https://vitejs.dev/guide/migration.html#remove-https-flag-and-https-true)

**Comment by edivados** [comment]
@indeyets 
> will it still be possible to specify cert/key manually? :)

Yes and if we go with using listhen's implementation it should support what listhen supports. See [listhen](https://github.com/unjs/listhen?tab=readme-ov-file#https)

@edygar 
>should it supported http: true? I'm asking because of [it got removed from vite 5](https://vitejs.dev/guide/migration.html#remove-https-flag-and-https-true)

Should be fine because true is not passed to vite. It's set to `false` or `{ cet, key }`. I will check with vite 5 just in case.

**Comment by edivados** [comment]
@nksaraf 
> Yeah I would want just https to work. Lets work with listhen to expose that, and in the meanwhile copy over that code and do it ourselves here?
> 
> Does listehn support https: true ?

Yes, see [here](https://github.com/unjs/listhen?tab=readme-ov-file#https). `resolveCertificate` isn't typed for it but it works. It merges true with the deafult config using defu. Will double check just to be sure.

>since https is a server concern it should be handled centrally. Why cant we just set the https field in the createViteHandler in the dev-server.js. We don't need to inform each build handler and dev handler. We can centralize this.

Should be good now. Copied the implementation over from listhen and converted the ts file to js. Not sure what to do with the `.d.ts` file. Leave it? Also should we add a note at the top of the file saying it's from listhen?

**Comment by nksaraf** [comment]
> Should be good now. Copied the implementation over from listhen and converted the ts file to js. Not sure what to do with the `.d.ts` file. Leave it? Also should we add a note at the top of the file saying it's from listhen?

Yup and add their license. We can also maybe just export it from my fork of listhen, `nksaraf/listhen` which `vinxi` currently uses.

And yeah we should support all the Https options listhen does and then we can pass to vite whatever it expects based on whatever version it is. I consider that internal implementation details

**Comment by edivados** [comment]
>We can also maybe just export it from my fork of listhen, `nksaraf/listhen` which `vinxi` currently uses.

I like that idea more then copying the file over. Only need to make `resolveCertificate` available. Do you want me to make a PR on `vinxi/listhen` so we can just import from there?

> And yeah we should support all the Https options listhen does and then we can pass to vite whatever it expects based on whatever version it is. I consider that internal implementation details

Good thing is we shouldn't have to do anything but take the return value from `resolveCertificate` and pass it to vite and listhen. If it turns out that when using a passphrase it returns an encrypted private key we maybe have to decrypt it first for vite but I have not looked into it. Basic usage worked.

**Comment by nksaraf** [comment]
> Do you want me to make a PR on [@vinxi/listhen](https://github.com/nksaraf/listhen) so we can just import from there?

Yup!! that would be great. that will make this simpler

**Comment by edivados** [comment]
Done. I did a PR against ws because it has the websocket stuff which is available here in dev right?

**Comment by nksaraf** [comment]
mergeed that and release at @vinxi/listhen@1.5.6. #127 bumps up our dependency. This PR can use than now for providing https functionality to vinxi.

**Comment by edivados** [comment]
Good to merge.

> [!NOTE]  
>Did a last min change so that `resolveCertificate` does not receive true but an empty object (for the type errors). We can make it more pretty later no need to block this any longer.

**Pull request merged**
