### PR TITLE
Change host to string for start command, to be able to set host

### PR DESCRIPTION
**Pull request by bondehagen**

### CODE REVIEW

**Comment by birkskyum** [comment]
This could be useful for dev as well. Seems like it's always localshost

**Comment by nksaraf** [comment]
can we pass host without any value and it gets exposed on the public API, thats the default nitro API and that works well. It should then be able to add a proper host to it.

**Comment by bondehagen** [comment]
> can we pass host without any value and it gets exposed on the public API, thats the default nitro API and that works well. It should then be able to add a proper host to it.

Not sure I follow. I'm only fixing a typo, host is not a boolean, but a string for the start coomand. My use case is to be able to bind to both ipv4 and ipv6 at the same time with `[::]`.

**Comment by bondehagen** [comment]
@nksaraf Can you merge this now?

**Comment by ryansolid** [comment]
Thanks

**Pull request merged**
